force-app/main/default/objects/Demo_Object__c/Demo_Object__c.object-meta.xml
<CustomObject
     >
    <historyRetentionPolicy n1:nil="true" />
    <label>Demo Object</label>
    <nameField>
        <label>Demo Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Object__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Keeping the sandboxes alive with this change</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Demo_Object__c/fields/External_URL__c.field-meta.xml
<CustomField>
    <fullName>External_URL__c</fullName>
    <label>External URL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>https://dev1.externalurl.com</fullName>
            </value>
            <value>
                <fullName>https://static.externalurl.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DemoObjectController.cls
public class DemoObjectController {
	// made a change in DEV2
    static public String getExternalURL(Demo_Object__c obj) {
        String url = obj.External_URL__c;	// made a change in DEV1
        return url;
    }
    
    static public String getDescription(Demo_Object__c obj) {
        String d = obj.Description__c;	// made a change in DEV1
        return d;
    	// made a change in DEV2
    }

}